src/objects/Attendance__c.object
<CustomObject>
    <fields>
        <fullName>Attendance_Status__c</fullName>
        <label>Attendance Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Enrolled</fullName>
                    <default>true</default>
                    <label>Enrolled</label>
                </value>
                <value>
                    <fullName>Attended</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Attendances</relationshipLabel>
        <relationshipName>Attendances</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Registration_Status__c</field>
                <operation>notEqual</operation>
                <value>Inactive, Withdrawn</value>
            </filterItems>
            <infoMessage>By default, Contacts who are inactive or who have withdrawn are not shown in this list - click on &quot;Show all results&quot; to see all Contacts regardless of Registration Status</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Attendances</relationshipLabel>
        <relationshipName>Attendances</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>DisableButtons__c</fullName>
        <formula>ISPICKVAL(Attendance_Status__c, &quot;Attended&quot;) || ISPICKVAL( Attendance_Status__c, &quot;Cancelled&quot;)</formula>
        <inlineHelpText>If true, then the attendance buttons on the Lightning page for Class Attendance management get diabled</inlineHelpText>
        <label>DisableButtons</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Notification_email_copy__c</fullName>
        <label>Notification email copy</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Student</fullName>
                    <default>true</default>
                    <label>Student</label>
                </value>
                <value>
                    <fullName>Leader</fullName>
                </value>
                <value>
                    <fullName>Assistant</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/Class__c.object
<CustomObject>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Full_Name__c</fullName>
        <formula>FirstName + &quot; &quot; +  LastName</formula>
        <label>Full Name</label>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/listAttendanceAPEXController.cls
public with sharing class listAttendanceAPEXController {
    
    @AuraEnabled
    public Static List<sObject> reQuery ( ID parentClassID ) {
                return [SELECT Id, Name, Role__c, Attendance_Status__c, Contact__r.ID,
                Contact__r.Name, Contact__r.Full_Name__c, Contact__r.Firstname, Contact__r.Lastname,
                	Notification_email_copy__c,DisableButtons__c FROM Attendance__c
               where Class__c = :parentClassID
                Order by Role__c DESC
               ];
    }
        
    
    @AuraEnabled
    public static List<sObject> getAttendances( ID parentClassID ) {
        system.debug('Passed in - parentClassID: ' + parentClassID );
        
        return reQuery (parentClassID);
    }
    
    @AuraEnabled
    public Static List<sObject> delAttendance (ID parentClassID, String attendeeName) {
        
        System.debug('Attendee record name passed in to delAttendance APEX Class: ' + attendeeName);
        
        try {
            delete [select id from Attendance__c Where Name = :attendeeName]; 
        } catch(DmlException e) {
            System.debug('An unexpected error has occurred: ' + e.getMessage());
        }
        
        system.debug('Refreshing attendance list for - parentClassID: ' + parentClassID );
        // Return the updated list of attendees on this class
        return reQuery (parentClassID);


    }
    
        @AuraEnabled
    public Static List<sObject> updAttendance (ID parentClassID, String attendeeName, String AttStatus) {
        Attendance__c Att = [SELECT Id, Attendance_Status__c FROM Attendance__c
               where Name = :attendeeName ];
        
        System.debug('Name passed in to updAttendance APEX Class: ' + attendeeName + ' status = ' + AttStatus);
        Att.Attendance_Status__c = AttStatus;
        
        try {
            update att;
        } catch(DmlException e) {
            System.debug('An unexpected error has occurred: ' + e.getMessage());
        }
        return reQuery (parentClassID);
    }
    

}