src/objects/Attendance__c.object
<CustomObject>
    <fields>
        <fullName>Attendance_Status__c</fullName>
        <label>Attendance Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Enrolled</fullName>
                    <default>true</default>
                    <label>Enrolled</label>
                </value>
                <value>
                    <fullName>Attended</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Attendances</relationshipLabel>
        <relationshipName>Attendances</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Registration_Status__c</field>
                <operation>notEqual</operation>
                <value>Inactive, Withdrawn</value>
            </filterItems>
            <infoMessage>By default, Contacts who are inactive or who have withdrawn are not shown in this list - click on &quot;Show all results&quot; to see all Contacts regardless of Registration Status</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Attendances</relationshipLabel>
        <relationshipName>Attendances</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Student</fullName>
                    <default>true</default>
                    <label>Student</label>
                </value>
                <value>
                    <fullName>Leader</fullName>
                </value>
                <value>
                    <fullName>Assistant</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/Class__c.object
<CustomObject>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact_Type__c</fullName>
        <label>Contact Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Student</fullName>
                    <default>true</default>
                    <label>Student</label>
                </value>
                <value>
                    <fullName>Parent</fullName>
                </value>
                <value>
                    <fullName>Staff</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Full_Name__c</fullName>
        <formula>FirstName + &quot; &quot; +  LastName</formula>
        <label>Full Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Registration_Status__c</fullName>
        <label>Registration Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Email Received</fullName>
                    <default>true</default>
                    <label>Email Received</label>
                </value>
                <value>
                    <fullName>Email Received &amp; Response Sent</fullName>
                </value>
                <value>
                    <fullName>Registered at Code Club</fullName>
                </value>
                <value>
                    <fullName>Registration Confirmed by SFDC</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Staff</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/classes/addChildController.cls
public class addChildController {
    @AuraEnabled
    public static List<contact> getContacts(String ParentId, String ContactType) {
        system.debug('Passed in - ParentID: ' + ParentId + ' ContactType: ' + ContactType);
        List<contact> totalList = new List<contact>();
        for(Contact cc : [SELECT id,Full_Name__c,Registration_Status__c from contact 
                          where Contact_Type__c = :ContactType
                         and Registration_Status__c != 'Withdrawn'
                         and id not in (Select Contact__c from Attendance__c
                                       where Class__c = :ParentId)
                          order by Full_Name__c]){
                              totalList.add(cc);
                          }	
        return totalList;
    }
    
    @AuraEnabled
    public static String addParentClass(String ParentId , List<String> lstOfContactIds, String Role){
		String retMsg;
        System.debug('Entering  addChildController.apxc - addParentClass' );
        list<Attendance__c> lstAttendance = new list<Attendance__c>();
        for(string sContactId : lstOfContactIds){
            Attendance__c oAtt = new Attendance__c();
            oAtt.Contact__c = sContactId;
            oAtt.Class__c = ParentId;
            if (Role == 'Student') {
                oAtt.Role__c = 'Student';
            } else {
                oAtt.Role__c = 'Assistant';
            }
            oAtt.Attendance_Status__c = 'Enrolled';
            lstAttendance.add(oAtt);
        }
        try {
            insert lstAttendance;
            System.debug('Added ' + lstAttendance + ' to the Class' );
            retMsg = 'SUCCESS';
        } catch(DmlException e) {
            System.debug('An unexpected error has occurred: ' + e.getMessage());
            retMsg = e.getMessage();
        }
       
        return retMsg;
    }
}